### PR TITLE
[W03] Add last year's tests and Artemis Example for StackyQueue

### PR DESCRIPTION
**Pull request by Flnn0**
#### General

- [x] I locally pass **all** tests or calculated manually the correct solutions on paper.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://github.com/JohannesStoehr/gad23-tests/blob/main/CONTRIBUTING.md).
- [x] The newly added tests do not reveal the solutions dynamically calculating the solutions as expected in the exercise.

### Description

The exercise looks like to be nearly the same as last year and my solution passes the Artemis tests.
I include the File `StackyQueueTest.java`, which tests the Artemis example for StackyQueue.
I also changed the File `ArrayHelper.java`, I include the methods checkUnderlyingArrayFirst(...) and checkUnderlyingArraySecond(...). These methods work as the methode checkUnderlyingArray(...) from last year.

#### Review
- [x] Review 1
- [x] Optional Review 2

### CODE REVIEW

**Review by ValentinGruener — APPROVED** [review]
Same as last year but Lgtm

**Review by LeoWoehler — APPROVED** [review]
LGTM

**Review by JennyKiener — APPROVED** [review]
looks good to me

**Comment by Flnn0** [comment]
@JohannesStoehr This PR is ready for merge

**Pull request merged**
