### PR TITLE
[W02] Add interval size 1 edge case logging test

### PR DESCRIPTION
**Pull request by ITegs**
#### General
- [x] I locally pass **all** tests or calculated manually the correct solutions on paper.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://github.com/JohannesStoehr/gad23-tests/blob/main/CONTRIBUTING.md).
- [x] The newly added tests do not reveal the solutions dynamically calculating the solutions as expected in the exercise.

### Description
Based on #20, the correct logging at an interval of size 1 is tested here.

#### Review
- [x] Review 1
- [x] Optional Review 2

### CODE REVIEW

**Comment by Anatoly03** [comment]
It's correct on paper, lgtm!

**Review by nilsreichardt — APPROVED** [review]
LGTM 👍

Nit: I just saw that the class is named `loggingTest`. Class names in Java should be written in `UpperCaseCamel` (see [Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.2.2-class-names)). Not important, but something that can be imported for future test 👍 

If "Nit" is new to you: [What does ‘nit’ mean in a code review?](https://onetwobytes.com/2021/11/09/nit-code-review/)

**Comment by nilsreichardt** [comment]
cc: @JohannesStoehr

**Comment by ITegs** [comment]
@nilsreichardt thanks for the hint, I will go like this in the future!

**Pull request merged**
