### PR TITLE
[*] pr-template: remove old comments + fix project title

### PR DESCRIPTION
**Pull request by ITegs**
#### General

- [x] I confirm that my tests, if any, are correct
    - [ ] Optional: I pass **all** artemis tests.
    - [ ] Optional: I pass **all** tests, that are added in this PR.
    - [ ] Optional: I calculated manually the correct solutions on paper.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://github.com/JohannesStoehr/gad23-tests/blob/main/CONTRIBUTING.md).
- [ ] The newly added tests do not reveal the solutions dynamically calculating the solutions as expected in the exercise.
- [x] Other students approved this Pull Request.

### Description

Old comment fragments in the PR-template from the Artemis project have been removed / adapted.

### CODE REVIEW

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Comment by Anatoly03** [comment]
What’s with the change in lines 9-11?

**Comment by ITegs** [comment]
> What’s with the change in lines 9-11?

autogenerated indents from my code formatter (2 spaces not 4)

**Comment by ITegs** [comment]
@JohannesStoehr can be merged

**Pull request merged**
