### PR TITLE
[W03] Added Artemis example for Dynamic Array

### PR DESCRIPTION
**Pull request by mbmueller**
#### General

- [x] I locally pass **all** tests or calculated manually the correct solutions on paper.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://github.com/JohannesStoehr/gad23-tests/blob/main/CONTRIBUTING.md).
- [x] The newly added tests do not reveal the solutions dynamically calculating the solutions as expected in the exercise.

#### Review
- [ ] Review 1
- [ ] Optional Review 2

### CODE REVIEW

**Review by Anatoly03 — APPROVED** [review]
lgtm

**Comment by mbmueller** [comment]
Sorry for the mess. Wanted to add the ExceptionTest but Github was down and produced some bugs in my commit history

**Review by Flnn0 — APPROVED** [review]
lgtm, but there are the nearly same test and more in #23.

**Comment by mbmueller** [comment]
There is at least no Test for the IllegalArgumentException

**Comment by Flnn0** [comment]
@mbmueller Thank you very much. I missed that, now it's implemented in my Tests.

**Pull request merged**
